main() {
    println("Message : ${"IllegalArgumentException"}")
    println("${"IllegalArgumentException"} - This is a message.")
    println("This is a message - ${"IllegalArgumentException"} - This is a message.")
    println("${"IllegalArgumentException"}")
    println("$")
    println("cangjie is very good \t\n!\n")
    println("${ 100 } is very \t!")
    println("I love huawei!!! \u{00000C}")
    println("{}")
    println("Hi! // This is not a comment.")
    println("Hi! $ // This is not a comment. ${"This is a string"}")
}